import Link from "next/link";
import { ArrowRight, Check, ChevronRight } from "lucide-react";
import { ConsultationBooking } from "@/components/ConsultationBooking";
import { FeatureVisual } from "@/components/FeatureVisual";
import { ProcessGlyph, type ProcessGlyphType } from "@/components/ProcessGlyph";
import { featureFamilyFor, featureProfile, type FeatureFamily } from "@/lib/feature-content";
import { groupByPath, routeByPath } from "@/lib/site-data";

type Copy = { kicker: string; headline: string; lead: string; outcome: string; benefits: string[]; steps: string[]; labels: string[] };
type Signature = { kicker: string; title: string; nodes: { icon: ProcessGlyphType; label: string; meta: string }[]; related: { icon: ProcessGlyphType; label: string }[] };

const signatures: Record<FeatureFamily, Signature> = {
  vehicle: { kicker: "DATENKETTE FAHRZEUG & TEIL", title: "Aus Fahrzeugdaten wird eine belastbare Teileentscheidung.", nodes: [{ icon: "scan", label: "Dokument", meta: "VIN · HSN/TSN" }, { icon: "vehicle", label: "Fahrzeug", meta: "Eindeutig zugeordnet" }, { icon: "match", label: "OE-Ergebnis", meta: "Direkt verwendbar" }], related: [{ icon: "vehicle", label: "Fahrzeugakte" }, { icon: "match", label: "Teilezuordnung" }, { icon: "order", label: "Angebot" }, { icon: "return", label: "Retourenprävention" }] },
  chat: { kicker: "DATENKETTE KUNDENDIALOG", title: "Aus einer Nachricht wird ein bearbeitbarer Vorgang.", nodes: [{ icon: "assistant", label: "Nachricht", meta: "Text · Bild · Dokument" }, { icon: "scan", label: "Datencheck", meta: "Fehlendes ergänzen" }, { icon: "order", label: "Anfrage", meta: "Im Verkauf bereit" }], related: [{ icon: "assistant", label: "WhatsApp" }, { icon: "vehicle", label: "Fahrzeugdaten" }, { icon: "match", label: "Teilewunsch" }, { icon: "order", label: "Verkauf" }] },
  stock: { kicker: "DATENKETTE WARENWIRTSCHAFT", title: "Bedarf, Beschaffung und Bestand bleiben synchron.", nodes: [{ icon: "flow", label: "Bedarf", meta: "Bestand & Nachfrage" }, { icon: "purchase", label: "Beschaffung", meta: "Bestellung steuern" }, { icon: "inventory", label: "Bestand", meta: "Bewegung dokumentiert" }], related: [{ icon: "match", label: "Artikel" }, { icon: "purchase", label: "Einkauf" }, { icon: "inventory", label: "Lager" }, { icon: "order", label: "Verfügbarkeit" }] },
  return: { kicker: "DATENKETTE RETOURE", title: "Jede Rückgabe bleibt mit ihrem Ursprung verbunden.", nodes: [{ icon: "return", label: "Rückgabe", meta: "Grund erfassen" }, { icon: "scan", label: "Prüfung", meta: "Zustand dokumentieren" }, { icon: "finance", label: "Abschluss", meta: "Gutschrift & Bestand" }], related: [{ icon: "order", label: "Ursprungsbeleg" }, { icon: "return", label: "Rückgabe" }, { icon: "inventory", label: "Bestand" }, { icon: "finance", label: "Gutschrift" }] },
  finance: { kicker: "DATENKETTE KASSE & FINANZEN", title: "Vom Verkauf bis zum gebuchten Beleg ohne Medienbruch.", nodes: [{ icon: "checkout", label: "Abschluss", meta: "Kasse & Zahlung" }, { icon: "finance", label: "Zuordnung", meta: "Konten & Posten" }, { icon: "record", label: "Übergabe", meta: "Beleg & Buchhaltung" }], related: [{ icon: "checkout", label: "Kasse" }, { icon: "finance", label: "Zahlungen" }, { icon: "record", label: "E-Rechnung" }, { icon: "flow", label: "DATEV-Übergabe" }] },
  mobile: { kicker: "DATENKETTE MOBILES ARBEITEN", title: "Vor Ort erfassen. Im System sofort weiterarbeiten.", nodes: [{ icon: "vehicle", label: "Vor Ort", meta: "Fahrzeug · Regal · Teil" }, { icon: "scan", label: "Erfassen", meta: "Foto & Status" }, { icon: "flow", label: "Synchron", meta: "Im Team verfügbar" }], related: [{ icon: "vehicle", label: "Fahrzeug" }, { icon: "inventory", label: "Lagerplatz" }, { icon: "record", label: "Dokumentation" }, { icon: "flow", label: "Synchronisierung" }] },
  core: { kicker: "DATENKETTE PARTSUNION", title: "Ein Vorgang verbindet jeden Arbeitsschritt.", nodes: [{ icon: "scan", label: "Erfassen", meta: "Einmal vollständig" }, { icon: "flow", label: "Bearbeiten", meta: "Im Team verbunden" }, { icon: "record", label: "Abschließen", meta: "Nachvollziehbar" }], related: [{ icon: "vehicle", label: "Fahrzeug & Teile" }, { icon: "assistant", label: "Kundendialog" }, { icon: "inventory", label: "Bestand & Einkauf" }, { icon: "finance", label: "Beleg & Zahlung" }] },
};

function copyFor(path: string, title: string, description: string): Copy {
  const base = { kicker: "PARTSUNION FEATURE", headline: title, lead: description, outcome: "Ein klarer Ablauf, der deinem Team jeden Tag Zeit spart.", benefits: ["Weniger manuelle Eingaben", "Alle Informationen an einem Ort", "Klare Zuständigkeiten im Team"], steps: ["Vorgang erfassen", "Daten automatisch ergänzen", "Prüfen und abschließen"], labels: ["Neuer Vorgang", "In Bearbeitung", "Erledigt"] };
  if (/betriebsassistent/.test(path)) return { kicker: "GEFÜHRTE PROZESSE", headline: title, lead: description, outcome: "Der Betriebsassistent führt dein Team sicher durch jeden Vorgang.", benefits: ["Nächsten Arbeitsschritt direkt erkennen", "Nur passende Informationen und Eingaben anzeigen", "Standards im Tagesgeschäft konsequent einhalten"], steps: ["Vorgang und Kontext verstehen", "Aufgabe eindeutig priorisieren", "Geführt und nachvollziehbar abschließen"], labels: ["Handlungsbedarf", "Nächster Schritt", "Sicher erledigt"] };
  if (/oe-|oem|vin|fahrzeug|teileermittlung|geschwindigkeit|retourenquote/.test(path)) return { kicker: "FAHRZEUG- & TEILEIDENTIFIKATION", headline: title, lead: description, outcome: "Vom Fahrzeug direkt zur verlässlichen Teilenummer.", benefits: ["Fahrzeugschein automatisch auslesen", "VIN und HSN/TSN sicher zuordnen", "Fehlbestellungen und Rückfragen reduzieren"], steps: ["Fahrzeugdaten erfassen", "OE-Nummern ermitteln", "Passendes Teil übernehmen"], labels: ["Fahrzeug erkannt", "OE-Abgleich", "Teil gefunden"] };
  if (/whatsapp|anfragen/.test(path)) return { kicker: "DIGITALER KUNDENDIALOG", headline: title, lead: description, outcome: "Aus unstrukturierten Nachrichten werden vollständige Teileanfragen.", benefits: ["Bilder und Fahrzeugschein automatisch erfassen", "Fehlende Angaben gezielt nachfragen", "Anfragen direkt an den Verkauf übergeben"], steps: ["Nachricht empfangen", "Fahrzeug & Teilewunsch ergänzen", "Anfrage im ERP bearbeiten"], labels: ["Neue Nachricht", "Daten vollständig", "Bereit für Verkauf"] };
  if (/lager|bestand|bestell|einkauf|disposition/.test(path)) return { kicker: "WARENWIRTSCHAFT & LAGER", headline: title, lead: description, outcome: "Bestand, Bedarf und Warenbewegung jederzeit nachvollziehbar.", benefits: ["Bestände zentral synchronisieren", "Bedarf frühzeitig erkennen", "Warenein- und -ausgänge sauber dokumentieren"], steps: ["Bedarf erkennen", "Ware bestellen oder reservieren", "Bestand automatisch aktualisieren"], labels: ["Bestand geprüft", "Bestellung offen", "Ware verbucht"] };
  if (/retour/.test(path)) return { kicker: "RETOUREN & REKLAMATIONEN", headline: title, lead: description, outcome: "Rückgaben ohne Zettelwirtschaft und offene Fragen.", benefits: ["Grund und Zustand dokumentieren", "Bilder direkt am Vorgang speichern", "Gutschrift und Rückversand nachverfolgen"], steps: ["Retoure aufnehmen", "Teil prüfen", "Gutschrift abschließen"], labels: ["Eingegangen", "In Prüfung", "Abgeschlossen"] };
  if (/kasse|finanz|rechnung|buchhaltung|banking|datev|tse|zugferd/.test(path)) return { kicker: "KASSE & FINANZEN", headline: title, lead: description, outcome: "Verkauf, Zahlung und Beleg bleiben lückenlos verbunden.", benefits: ["Belege direkt aus Vorgängen erzeugen", "Zahlungen und Konten abgleichen", "Relevante Standards integriert unterstützen"], steps: ["Verkauf abschließen", "Zahlung zuordnen", "Beleg an Buchhaltung übergeben"], labels: ["Kasse", "Bezahlt", "Verbucht"] };
  if (/app|mobil/.test(path)) return { kicker: "MOBIL ARBEITEN", headline: title, lead: description, outcome: "Wichtige Vorgänge direkt am Fahrzeug, Regal oder Lagerplatz erledigen.", benefits: ["Teile und Vorgänge mobil aufrufen", "Fotos direkt zuordnen", "Status ohne Umweg aktualisieren"], steps: ["Vorgang öffnen", "Informationen vor Ort ergänzen", "Änderung sofort synchronisieren"], labels: ["Mobil geöffnet", "Foto ergänzt", "Synchronisiert"] };
  return base;
}

function themeFor(path: string) {
  if (/whatsapp|anfragen/.test(path)) return "feature-theme-chat";
  if (/oe-|oem|vin|fahrzeug|teileermittlung|retourenquote/.test(path)) return "feature-theme-vehicle";
  if (/lager|bestand|bestell|einkauf|disposition/.test(path)) return "feature-theme-stock";
  if (/retour/.test(path)) return "feature-theme-return";
  if (/kasse|finanz|rechnung|buchhaltung|banking|datev|tse|zugferd/.test(path)) return "feature-theme-finance";
  if (/app|mobil/.test(path)) return "feature-theme-mobile";
  return "feature-theme-core";
}

export function FeaturePage({ path }: { path: string }) {
  const route = routeByPath(path)!;
  const group = groupByPath(path);
  const copy = copyFor(path, route.label, route.description);
  const theme = themeFor(path);
  const profile = featureProfile(path, route.label, route.description);
  const signature = signatures[featureFamilyFor(path)];
  const icons = signature.nodes.map((node) => node.icon);
  return <>
    <section className={`feature-hero ${theme}`}><div className="container breadcrumbs"><Link href="/">Startseite</Link><ChevronRight />{group && <><Link href={group.href}>{group.label}</Link><ChevronRight /></>}<span>{route.label}</span></div><div className="container feature-hero-grid"><div className="feature-hero-copy"><p className="eyebrow">{copy.kicker}</p><h1>{copy.headline}</h1><p>{copy.lead} Partsunion verbindet diesen Schritt direkt mit den vor- und nachgelagerten Abläufen deines Betriebs.</p><div className="hero-actions"><Link className="button button-primary" href="/beratung">Persönlich ansehen <ArrowRight /></Link><Link className="text-link" href="/produktdaten">Produktansichten <ArrowRight /></Link></div><div className="feature-proof"><span><Check /> Für Autoteilehändler entwickelt</span><span><Check /> In deinen Workflow integriert</span></div></div><FeatureVisual path={path} labels={copy.labels} /></div></section>

    <section className={`feature-signature ${theme}`}><div className="container feature-signature-grid"><div><p className="eyebrow">{signature.kicker}</p><h2>{signature.title}</h2></div><div className="feature-signal-track">{signature.nodes.map((node, index) => <article key={node.label}><span>0{index + 1}</span><ProcessGlyph type={node.icon} /><div><strong>{node.label}</strong><small>{node.meta}</small></div>{index < signature.nodes.length - 1 && <ArrowRight />}</article>)}</div></div></section>

    <section className={`section container feature-value ${theme}`}><div><p className="eyebrow">DEIN VORTEIL</p><h2>{copy.outcome}</h2><p>Keine isolierte Zusatzfunktion: Der gesamte Vorgang bleibt mit Kunde, Fahrzeug, Teil, Bestand und Beleg verbunden.</p></div><p className="scroll-hint">Seitlich wischen <ArrowRight /></p><div className="feature-benefit-grid">{copy.benefits.map((benefit, index) => <article key={benefit}><span><ProcessGlyph type={icons[index]} /></span><h3>{benefit}</h3><p>Informationen werden genau dort bereitgestellt, wo dein Team sie im nächsten Schritt braucht.</p></article>)}</div></section>

    <section className={`feature-workflow ${theme}`}><div className="container"><div className="feature-workflow-heading"><p className="eyebrow">SO FUNKTIONIERT ES</p><h2>Drei Schritte. Ein sauberer Vorgang.</h2></div><div className="workflow-steps">{copy.steps.map((step, index) => <article key={step}><span>0{index + 1}</span><div><h3>{step}</h3><p>{index === 0 ? "Die vorhandenen Informationen werden zentral aufgenommen." : index === 1 ? "Partsunion ergänzt Daten und führt durch die nächsten Aufgaben." : "Der Vorgang wird dokumentiert und direkt weiterverarbeitet."}</p></div>{index < 2 && <ArrowRight />}</article>)}</div></div></section>

    <section className={`feature-context ${theme}`}><div className="container feature-context-grid"><div className="feature-context-copy"><p className="eyebrow">IM ECHTEN TAGESGESCHÄFT</p><h2>Wo {route.label} im Betrieb wirkt.</h2><p>{profile.result} Die Funktion setzt dort an, wo Informationen entstehen, und hält sie für alle folgenden Arbeitsschritte verfügbar.</p><dl><div><dt>Geeignet für</dt><dd>{profile.audience}</dd></div><div><dt>Ausgangspunkt</dt><dd>{profile.source}</dd></div><div><dt>Direkt verbunden mit</dt><dd>{profile.connection}</dd></div></dl></div><div className="feature-scenario-grid">{profile.scenarios.map((scenario, index) => <article key={scenario.title}><span>0{index + 1}</span><div><h3>{scenario.title}</h3><p>{scenario.text}</p></div></article>)}</div></div></section>

    <section className={`section container feature-detail ${theme}`}><div><p className="eyebrow">TEIL DER GESAMTEN PLATTFORM</p><h2>Wirkt nicht allein, sondern im Zusammenspiel.</h2><p>Damit dein Team nicht zwischen Programmen, Chats und Listen springen muss, teilt diese Funktion Daten mit allen relevanten Bereichen von Partsunion.</p><Link className="button button-outline" href="/plattform">Gesamte Plattform entdecken <ArrowRight /></Link></div><div className="feature-detail-grid">{signature.related.map((item) => <article key={item.label}><ProcessGlyph type={item.icon} /><span>{item.label}</span></article>)}</div></section>

    <section className={`section container feature-faq ${theme}`}><div className="feature-faq-heading"><p className="eyebrow">HÄUFIGE FRAGEN</p><h2>{route.label} kurz erklärt.</h2><p>Konkrete Antworten für die Einordnung im Autoteilehandel.</p></div><div className="feature-faq-list">{profile.faqs.map((item, index) => <details key={item.question} open={index === 0}><summary><span>0{index + 1}</span>{item.question}<i /></summary><p>{item.answer}</p></details>)}</div></section>

    <section className={`section contact-section feature-contact container ${theme}`}><div className="contact-heading"><p className="eyebrow">LIVE IN DEINEM PROZESS</p><h2>Passt das zu deinem Betrieb?</h2><p>Wähle direkt einen Termin. Wir führen dich anschließend genau durch die Funktionen, die für dein Team relevant sind.</p></div><ConsultationBooking compact /></section>
  </>;
}
