import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Check, ChevronRight, CircleCheck, Clock3, Mail, MapPin, Minus, ShieldCheck, X } from "lucide-react";
import { ContactForm } from "@/components/ContactForm";
import { ConsultationBooking } from "@/components/ConsultationBooking";
import { MobileComparison } from "@/components/MobileComparison";
import { ProcessGlyph } from "@/components/ProcessGlyph";
import { ProductShot, type ProductShotVariant } from "@/components/ProductShot";
import { routeByPath } from "@/lib/site-data";

const Crumbs = ({ title }: { title: string }) => <div className="container breadcrumbs"><Link href="/">Startseite</Link><ChevronRight /><span>{title}</span></div>;

export function ContactPage({ consultation = false }: { consultation?: boolean }) {
  return <>
    <section className="special-heading"><Crumbs title={consultation ? "Beratung" : "Kontakt"} /><div className="container special-heading-copy"><p className="eyebrow">{consultation ? "PERSÖNLICHE PRODUKTBERATUNG" : "DIREKTER KONTAKT"}</p><h1>{consultation ? "Lass uns deinen Teilehandel gemeinsam ansehen." : "Wie können wir dir helfen?"}</h1><p>{consultation ? "In einem kurzen Gespräch klären wir, welche Abläufe dir heute Zeit kosten und wie Partsunion sie verbinden kann." : "Ob Produktfrage, Partnerschaft oder Support: Schreib uns – wir bringen dein Anliegen direkt an die richtige Stelle."}</p></div></section>
    <section className="section container contact-page-grid"><div className="contact-aside"><h2>{consultation ? "30 Minuten für deinen konkreten Ablauf." : "Direkt und persönlich."}</h2><p>{consultation ? "Wir schauen auf deinen Betrieb, eure Programme und den Weg von der Anfrage bis zu Beleg, Zahlung und Rückabwicklung." : "Ob Produktfrage, Partnerschaft oder Support: Wir bringen dein Anliegen direkt an die richtige Stelle."}</p><div className="contact-points"><span><Clock3 /> {consultation ? "30 Minuten · Europe/Berlin" : "Schnelle persönliche Rückmeldung"}</span><span><CircleCheck /> Unverbindliches Erstgespräch</span><span><ShieldCheck /> Deine Angaben bleiben geschützt</span></div>{consultation && <ol className="consultation-agenda"><li><span>01</span><div><strong>Dein Betrieb</strong><small>Sortiment, Team und heutige Programme</small></div></li><li><span>02</span><div><strong>Passende Funktionen</strong><small>Vom Fahrzeug bis zur Buchhaltung</small></div></li><li><span>03</span><div><strong>Nächster Schritt</strong><small>Einführung, Daten und konkreter Umfang</small></div></li></ol>}<div className="contact-direct"><a href="mailto:info@partsunion.de"><Mail /> <span><small>E-Mail</small>info@partsunion.de</span></a><span><MapPin /> <span><small>Standort</small>Brühl, Deutschland</span></span></div></div>{consultation ? <ConsultationBooking /> : <ContactForm />}</section>
  </>;
}

const comparisonRows = [
  { label: "Automatische OE-Ermittlung", partsunion: "Direkt integriert", erp: "Branchenlösung nötig", sheets: "Nur manuell", pu: "yes", ge: "no", sh: "no" },
  { label: "WhatsApp bis Angebot und Zahlung", partsunion: "Durchgängiger Ablauf", erp: "Zusatzlösungen nötig", sheets: "Nicht automatisiert", pu: "yes", ge: "no", sh: "no" },
  { label: "Verkauf, Einkauf und Lager", partsunion: "Gemeinsame Datenbasis", erp: "Je nach Modulumfang", sheets: "Listen bleiben getrennt", pu: "yes", ge: "partial", sh: "no" },
  { label: "Angebot bis Rechnung", partsunion: "Verbundene Belegkette", erp: "Typische ERP-Funktion", sheets: "Bezüge manuell pflegen", pu: "yes", ge: "yes", sh: "no" },
  { label: "Bestand, Reservierung, Beschaffung", partsunion: "Automatisch verbunden", erp: "Je nach Lagerlogik", sheets: "Eigene Regeln nötig", pu: "yes", ge: "partial", sh: "no" },
  { label: "Gebrauchtteile mit Herkunft und Zustand", partsunion: "Am konkreten Einzelteil", erp: "Sondermodell nötig", sheets: "Manuell organisiert", pu: "yes", ge: "no", sh: "partial" },
  { label: "Dynamische Masken und Assistent", partsunion: "Im Ablauf integriert", erp: "Nicht branchenspezifisch", sheets: "Nicht verfügbar", pu: "yes", ge: "no", sh: "no" },
  { label: "Retouren und Reklamationen", partsunion: "Mit Ursprungsbeleg", erp: "Je nach Modulumfang", sheets: "Manuelle Nachverfolgung", pu: "yes", ge: "partial", sh: "no" },
  { label: "Kasse, Banking und Buchhaltung", partsunion: "Im Vorgang verbunden", erp: "Je nach Edition", sheets: "Weitere Systeme nötig", pu: "yes", ge: "partial", sh: "no" },
];

function CompareIcon({ value }: { value: string }) {
  if (value === "yes") return <Check aria-label="Ja" />;
  if (value === "partial") return <Minus aria-label="Teilweise" />;
  return <X aria-label="Nein" />;
}

export function ComparisonPage() {
  return <>
    <section className="special-heading comparison-heading"><Crumbs title="Systeme vergleichen" /><div className="container special-heading-copy"><p className="eyebrow">EINE ENTSCHEIDUNG FÜR DEINEN BETRIEB</p><h1>Welches System passt zu deinem Teilehandel?</h1><p>Vergleiche mit deinen eigenen Arbeitsabläufen. Wichtig ist, welche Daten und Schritte bereits zusammengehören – und was du über Module, Schnittstellen oder eigene Regeln verbinden musst.</p><div className="hero-actions"><a className="button button-primary" href="#vergleich">Vergleich öffnen <ArrowRight /></a><Link className="text-link" href="/beratung">Anforderungen besprechen <ArrowRight /></Link></div></div></section>

    <section className="section container comparison-section" id="vergleich"><div className="section-top"><div><p className="eyebrow">DREI ANSÄTZE IM ÜBERBLICK</p><h2>Was ist direkt im System verbunden?</h2><p className="section-lead">Der konkrete Umfang allgemeiner ERP-Systeme hängt von Edition, Einrichtung und Anbindungen ab. Die Tabelle zeigt typische Ausgangslagen.</p></div><div className="comparison-legend"><span><Check /> direkt</span><span><Minus /> abhängig</span><span><X /> Zusatzweg</span></div></div><div className="comparison-table-wrap"><table className="comparison-table"><caption>Vergleich direkt verbundener Funktionen in Partsunion, allgemeinem ERP und Tabellen</caption><thead><tr><th scope="col">Prüfpunkt</th><th scope="col" className="featured-col"><span>Branchenspezifisch</span>Partsunion</th><th scope="col">Allgemeines ERP / WaWi</th><th scope="col">Tabellen</th></tr></thead><tbody>{comparisonRows.map((row) => <tr key={row.label}><th scope="row">{row.label}</th><td className="featured-col"><CompareIcon value={row.pu} /><span>{row.partsunion}</span></td><td><CompareIcon value={row.ge} /><span>{row.erp}</span></td><td><CompareIcon value={row.sh} /><span>{row.sheets}</span></td></tr>)}</tbody></table></div><MobileComparison rows={comparisonRows} /><p className="comparison-disclaimer">Ein Haken bezeichnet eine direkt verfügbare oder typische Systemfunktion. „Abhängig“ bedeutet, dass Umfang und Verbindung von Edition oder Einrichtung abhängen. Prüfe den konkreten Leistungsumfang immer im Angebot.</p></section>

    <section className="comparison-decision"><div className="container"><div className="comparison-decision-head"><p className="eyebrow">DIE PASSENDE WAHL TREFFEN</p><h2>Dein Bedarf gibt die Richtung vor.</h2></div><div className="decision-grid"><article><span>01</span><h3>Branchenspezifisches System</h3><p>Sinnvoll, wenn Fahrzeug- und OE-Bezug, Teileausführungen und Bestandslogik für Neu- oder Gebrauchtteile regelmäßig entscheidend sind.</p></article><article><span>02</span><h3>Allgemeine Warenwirtschaft</h3><p>Passend, wenn die gewählte Konfiguration deine Abläufe bereits abdeckt und Schnittstellen, Know-how und Einführungsaufwand stimmen.</p></article><article><span>03</span><h3>Tabellen und Einzeltools</h3><p>Praktikabel für sehr einfache Abläufe. Mit wachsendem Volumen steigt jedoch der Aufwand für Zuordnung, Status und Nachverfolgung.</p></article></div></div></section>

    <section className="section contact-section container"><div className="contact-heading"><p className="eyebrow">VERGLEICH FÜR DEINEN BETRIEB</p><h2>Prüfe Partsunion an deinen echten Vorgängen.</h2><p>Im Gespräch gehen wir deine Prozesse, Programme, Anbindungen und Datenübernahme durch. Danach kannst du anhand eines konkreten Umfangs entscheiden.</p></div><ConsultationBooking compact /></section>
  </>;
}

export function PricingPage() {
  return <>
    <section className="special-heading special-heading-center"><Crumbs title="Kosten" /><div className="container special-heading-copy"><p className="eyebrow">TRANSPARENT UND PASSEND ZU DEINEM BETRIEB</p><h1>Ein System. Ein passender Umfang.</h1><p>Dein Preis richtet sich nach dem Setup, das dein Teilehandel wirklich braucht – ohne unnötige Module und überraschende Zusatzwege.</p></div></section>
    <section className="section container pricing-layout"><div className="pricing-card"><p className="eyebrow">PARTSUNION KOMPLETT</p><h2>Individuell kalkuliert</h2><p className="price-lead">Auf Basis von Team, Sortiment, Standorten und gewünschter Automatisierung.</p><ul>{["ERP & Warenwirtschaft", "OE-Ermittlung und Fahrzeugdaten", "Einkauf, Lager und Retouren", "Kasse, Buchhaltung und Banking", "Einführung und Datenübernahme"].map((item) => <li key={item}><Check />{item}</li>)}</ul><Link className="button button-primary" href="/beratung">Persönliches Angebot anfragen <ArrowRight /></Link></div><div className="pricing-side"><p className="eyebrow">SO ENTSTEHT DEIN ANGEBOT</p>{[["01","Betrieb verstehen","Wir sprechen über Sortiment, Team und aktuelle Systeme."],["02","Umfang festlegen","Gemeinsam wählen wir Funktionen und Automatisierungen."],["03","Sauber starten","Einführung und Datenübernahme werden direkt eingeplant."]].map(([n,h,p]) => <article key={n}><span>{n}</span><div><h3>{h}</h3><p>{p}</p></div></article>)}</div></section>
    <section className="pricing-components"><div className="container"><div className="section-top"><div><p className="eyebrow">SAUBER AUFGESCHLÜSSELT</p><h2>Drei Bestandteile. Klar getrennt.</h2></div><p className="section-lead">Damit du Angebote sinnvoll vergleichen kannst, werden laufende Nutzung, Einführung und externe Anbindungen einzeln betrachtet.</p></div><div className="pricing-component-grid">{[["flow","01","Software & Nutzung","Arbeitsbereiche, Nutzer und gewünschte Automatisierung bestimmen den laufenden Umfang."],["record","02","Einrichtung & Daten","Prüfung, Übernahme, Einrichtung und Schulung werden einmalig geplant."],["finance","03","Anbindungen & Fremdkosten","Kataloge, Lieferanten oder Zahlungsdienste können eigene Konditionen haben."]].map(([icon,n,title,text]) => <article key={n}><ProcessGlyph type={icon as "flow" | "record" | "finance"} /><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="pricing-start"><div className="container pricing-start-grid"><div><p className="eyebrow">DER WEG IN DEINEN BETRIEB</p><h2>Einführung in überschaubaren Schritten.</h2><p>Vom Prozesscheck über Daten und Team bis zum koordinierten Start – jeder Schritt wird gemeinsam vorbereitet.</p><Link className="button button-light" href="/einfuehrung">Einführung ansehen <ArrowRight /></Link></div><div className="pricing-track" aria-label="Einführungsablauf"><span><i>01</i>Prozesse klären</span><span><i>02</i>Daten vorbereiten</span><span><i>03</i>Team trainieren</span><span><i>04</i>Gemeinsam starten</span></div></div></section>
  </>;
}

export function AboutPage() {
  return <>
    <section className="special-heading"><Crumbs title="Über Partsunion" /><div className="container special-heading-copy"><p className="eyebrow">ÜBER PARTSUNION</p><h1>Software aus dem Alltag des Autoteilehandels.</h1><p>Partsunion verbindet Branchenwissen mit moderner Technologie – damit Teilehändler weniger verwalten und mehr Zeit für Kunden, Sortiment und Wachstum haben.</p></div></section>
    <section className="section container about-grid"><div><p className="eyebrow">UNSERE MISSION</p><h2>Jeder Vorgang soll einfach nachvollziehbar sein.</h2></div><div><p>Der Teilehandel ist schnell, datenintensiv und voller Sonderfälle. Deshalb denken wir nicht in einzelnen Funktionen, sondern in vollständigen Abläufen: vom Fahrzeugschein über die OE-Nummer bis zu Rechnung, Zahlung oder Retoure.</p><p>Das Ergebnis ist eine Plattform, die Teams durch ihre tägliche Arbeit führt und Informationen genau dort zusammenbringt, wo sie gebraucht werden.</p></div></section>
    <section className="about-story"><div className="container about-story-grid"><figure><Image src="/images/parts-specialist-workshop.jpg" alt="Teilespezialist prüft ein Ersatzteil im Betrieb" fill sizes="(max-width: 760px) 100vw, 50vw" /><figcaption>AUS DER PRAXIS DES TEILEHANDELS</figcaption></figure><div><p className="eyebrow">WAS UNS LEITET</p><h2>Technik, die den echten Ablauf versteht.</h2>{[["vehicle","Fahrzeug zuerst","Jede Suche beginnt mit einer sauberen Identifikation."],["flow","Vorgang statt Insellösung","Informationen wandern ohne Medienbruch durch den Betrieb."],["assistant","Menschen im Mittelpunkt","Automatisierung unterstützt das Team bei der Entscheidung."]].map(([icon,title,text]) => <article key={title}><ProcessGlyph type={icon as "vehicle" | "flow" | "assistant"} /><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
    <section className="about-band"><div className="container"><div><strong>56</strong><span>Marken mit Nutzungsrechten</span></div><div><strong>80%</strong><span>der weltweiten VINs decodierbar</span></div><div><strong>1</strong><span>System für den gesamten Betrieb</span></div></div></section>
  </>;
}

export function LegalPage({ path }: { path: string }) {
  const route = routeByPath(path)!;
  return <><section className="special-heading legal-heading"><Crumbs title={route.label} /><div className="container special-heading-copy"><p className="eyebrow">RECHTLICHES</p><h1>{route.label}</h1><p>{route.description}</p></div></section><section className="section container legal-copy"><aside><strong>PartsUnion UG (haftungsbeschränkt)</strong><span>Brühl, Deutschland</span><a href="mailto:info@partsunion.de">info@partsunion.de</a></aside><article><h2>{route.label}</h2><p>Hier findest du die rechtlichen Informationen rund um die Nutzung der Partsunion Website und Plattform.</p><h3>Geltungsbereich und Anbieter</h3><p>Die Angaben beziehen sich auf das Angebot der PartsUnion UG (haftungsbeschränkt). Für rechtsverbindliche Anfragen erreichst du uns unter info@partsunion.de.</p><h3>Aktualität der Informationen</h3><p>Rechtliche Inhalte werden bei Bedarf aktualisiert. Maßgeblich ist die jeweils veröffentlichte Fassung.</p></article></section></>;
}

export function ArticlePage({ path }: { path: string }) {
  const route = routeByPath(path)!;
  const shot: ProductShotVariant = /whatsapp|anfragen/.test(path) ? "whatsapp" : /oe|fahrzeug|vin/.test(path) ? "oe" : /lager|bestand/.test(path) ? "inventory" : "order";
  return <><article className="article-page"><header><Crumbs title={route.label} /><div className="container article-header"><p className="eyebrow">PARTSUNION WISSEN</p><h1>{route.label}</h1><p>{route.description}</p><div><span>Praxiswissen</span><span>6 Minuten Lesezeit</span></div><div className="article-visual"><span>PRAXIS / PRODUKTANSICHT</span><ProductShot variant={shot} priority /></div></div></header><div className="container article-layout"><aside><strong>In diesem Beitrag</strong><a href="#ausgangslage">Ausgangslage</a><a href="#praxis">Praxis</a><a href="#fazit">Fazit</a></aside><div><p className="article-intro">Im Autoteilehandel entscheiden Geschwindigkeit und Genauigkeit darüber, ob aus einer Anfrage ein guter Auftrag wird. Gleichzeitig müssen Fahrzeugdaten, Teileinformationen und kaufmännische Abläufe sauber zusammenspielen.</p><h2 id="ausgangslage">Worauf es im Tagesgeschäft ankommt</h2><p>Ein durchgängiger Prozess beginnt bei vollständigen Daten. Wenn Fahrzeuginformationen, Teilewunsch und Kundendaten strukturiert vorliegen, kann dein Team schneller prüfen, anbieten und beschaffen.</p><div className="article-callout"><strong>Praxis-Tipp</strong><p>Lege Informationen nur einmal an und nutze sie anschließend in Angebot, Bestellung, Lager, Rechnung und Retoure weiter.</p></div><div className="article-flow" aria-label="Durchgängiger Arbeitsablauf">{[["scan","Erfassen"],["match","Zuordnen"],["record","Weiterführen"]].map(([icon,label],index) => <div key={label}><ProcessGlyph type={icon as "scan" | "match" | "record"} /><span>0{index + 1}</span><strong>{label}</strong></div>)}</div><h2 id="praxis">Abläufe konsequent verbinden</h2><p>Insellösungen erzeugen Rückfragen und doppelte Eingaben. Eine branchenspezifische Plattform hält jeden Schritt am selben Vorgang und macht den aktuellen Status für alle Beteiligten sichtbar.</p><h2 id="fazit">Fazit</h2><p>Die beste Automatisierung nimmt deinem Team Routinearbeit ab, ohne den Überblick zu verlieren. Partsunion setzt deshalb auf klare Workflows, nachvollziehbare Daten und Funktionen, die direkt zum Teilehandel passen.</p><Link className="button button-primary" href="/beratung">Im eigenen Betrieb ansehen <ArrowRight /></Link></div></div></article></>;
}
